DROP TABLE COMPOSITION CASCADE CONSTRAINTS PURGE;
DROP TABLE PIECE CASCADE CONSTRAINTS PURGE;
DROP TYPE EquipeTabT;
DROP TYPE EquipeT;
drop type QualiteList;
DROP TYPE IndicesQualiteT;

create or replace type EquipeT as object (
    nomEquipe varchar(255), 
    fonctionEquipe varchar(255)
);
/
create type EquipeTabT as table of EquipeT;
/

create or replace type IndicesQualiteT as object (
    nom varchar(255),
    valeur int,
    poids int
);
/
create type QualiteList as VARRAY(10) of IndicesQualiteT;
/

CREATE TABLE PIECE (
    idPiece NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(255),
    description VARCHAR2(255),
    prixUnitaire NUMBER(6,2),
    estComposee NUMBER(1) CHECK (estComposee IN (0,1)),
    DateDebut DATE,
    DateFin DATE,
    Equipe EquipeTabT,
    IndicesQualite QualiteList
)
nested table Equipe store as EquipeTab;

CREATE TABLE COMPOSITION (
    idComposee NUMBER,
    idComposant NUMBER,
    quantite NUMBER,
    PRIMARY KEY (idComposee, idComposant),
    FOREIGN KEY (idComposee) REFERENCES PIECE(idPiece) ON DELETE CASCADE,
    FOREIGN KEY (idComposant) REFERENCES PIECE(idPiece) ON DELETE CASCADE
);



